version: '3.6'

services:

  kg-db:
    image: ambiverse/kg-db-neo4j
    restart: always
    deploy:
      replicas: 1
    environment:
      DUMP_NAME: yago_aida_en20180120_cs20180120_de20180120_es20180120_ru20180120_zh20180120
      NEO4J_dbms_active__database: yago_aida_en20180120_cs20180120_de20180120_es20180120_ru20180120_zh20180120.db
      NEO4J_dbms_memory_pagecache_size: 8G
      NEO4J_dbms_memory_heap_initial__size: 8G
      NEO4J_dbms_memory_heap_max__size: 12G
      NEO4J_dbms_connectors_default__listen__address: 0.0.0.0
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_AUTH: neo4j/neo4j_pass
    ulimits:
      nofile:
        40000
    volumes:
      - type: volume
        source: dbdata
        target: /data
      - type: tmpfs
        target: /var/tmp/data
        tmpfs:
          size: 107374182400
    healthcheck:
      test: curl -sS http://127.0.0.1:7474/browser/ || exit 1
      interval: 1m
      timeout: 60s
      retries: 15
      start_period: 60m
    networks:
      kgnet:
        aliases:
          - kg-db

  kg:
    image: ambiverse/ambiverse-kg
    restart: always
    deploy:
      replicas: 1 # Increase the number of replicas if you want to scale horizontally
      resources:
        limits:
          #cpus: "1"
          memory: 16G
      restart_policy:
        condition: on-failure
    depends_on:
      - kg-db
    ports:
      - 8080:8080
    networks:
      - kgnet
    healthcheck:
      test: curl -sS http://127.0.0.1:8080/v2/knowledgegraph/entities/Q567 || exit 1
      interval: 1m
      timeout: 60s
      retries: 10
      start_period: 10s

volumes:
  dbdata:

networks:
  kgnet: