/*
 * Knowledge Graph Web Service
 * The Knowledge Graph Web Service lets you find entities and categories in the knowledge graph. This service is particularly suited to be run as a second step after the NLU Service has been used for linking ambiguous names in natural-language texts to entities. With this service, you can now explore these entities further.
 *
 * OpenAPI spec version: v2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.mpg.mpi_inf.ambiversenlu.kg.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.HashMap;
import java.util.Map;

/**
 * CategoriesResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2019-10-24T12:54:00.720Z[GMT]")public class CategoriesResponse   {
  @JsonProperty("categories")
  private Map<String, Category> categories = null;

  public CategoriesResponse categories(Map<String, Category> categories) {
    this.categories = categories;
    return this;
  }

  public CategoriesResponse putCategoriesItem(String key, Category categoriesItem) {
    if (this.categories == null) {
      this.categories = new HashMap<String, Category>();
    }
    this.categories.put(key, categoriesItem);
    return this;
  }

  /**
   * a (id, Category) map. &#x60;YAGO3:&lt;wikicat_Billionaires&gt;&#x60; is an example key.
   * @return categories
   **/
  @JsonProperty("categories")
  @Schema(description = "a (id, Category) map. `YAGO3:<wikicat_Billionaires>` is an example key.")
  @JsonInclude(JsonInclude.Include.NON_NULL)
  public Map<String, Category> getCategories() {
    return categories;
  }

  public void setCategories(Map<String, Category> categories) {
    this.categories = categories;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CategoriesResponse categoriesResponse = (CategoriesResponse) o;
    return Objects.equals(this.categories, categoriesResponse.categories);
  }

  @Override
  public int hashCode() {
    return Objects.hash(categories);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CategoriesResponse {\n");

    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
