/*
 * Knowledge Graph Web Service
 * The Knowledge Graph Web Service lets you find entities and categories in the knowledge graph. This service is particularly suited to be run as a second step after the NLU Service has been used for linking ambiguous names in natural-language texts to entities. With this service, you can now explore these entities further.
 *
 * OpenAPI spec version: v2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.mpg.mpi_inf.ambiversenlu.kg.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.HashMap;
import java.util.Map;
import javax.validation.constraints.*;

/**
 * EntitiesResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2019-10-24T12:54:00.720Z[GMT]")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class EntitiesResponse   {
  @JsonProperty("entities")
  private Map<String, Entity> entities = new HashMap<String, Entity>();

  public EntitiesResponse entities(Map<String, Entity> entities) {
    this.entities = entities;
    return this;
  }

  public EntitiesResponse putEntitiesItem(String key, Entity entitiesItem) {
    this.entities.put(key, entitiesItem);
    return this;
  }

  /**
   * a (id, Entity) map. &#x60;http://www.wikidata.org/entity/Q1137062&#x60; is an example key.
   * @return entities
   **/
  @JsonProperty("entities")
  @Schema(required = true, description = "a (id, Entity) map. `http://www.wikidata.org/entity/Q1137062` is an example key.")
  @NotNull
  public Map<String, Entity> getEntities() {
    return entities;
  }

  public void setEntities(Map<String, Entity> entities) {
    this.entities = entities;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntitiesResponse entitiesResponse = (EntitiesResponse) o;
    return Objects.equals(this.entities, entitiesResponse.entities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entities);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntitiesResponse {\n");

    sb.append("    entities: ").append(toIndentedString(entities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
