/*
 * Knowledge Graph Service
 * The Knowledge Graph Service lets you find entities and categories in the knowledge graph. This service is particularly suited to be run as a second step after the Entity Linking Service has been used for linking ambiguous names in natural-language texts to entities. With this service, you can now explore these entities further. 
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.mpg.mpi_inf.ambiversenlu.kg.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Image
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-03-13T15:01:58.186Z")
public class Image   {
  @JsonProperty("url")
  private String url = null;

  @JsonProperty("licenses")
  private List<License> licenses = null;

  @JsonProperty("author")
  private Author author = null;

  public Image url(String url) {
    this.url = url;
    return this;
  }

  /**
   * The public url of the image
   * @return url
   **/
  @JsonProperty("url")
  @ApiModelProperty(example = "https://upload.wikimedia.org/wikipedia/commons/3/38/Jack_Ma_2008.jpg", value = "The public url of the image")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Image licenses(List<License> licenses) {
    this.licenses = licenses;
    return this;
  }

  public Image addLicensesItem(License licensesItem) {
    if (this.licenses == null) {
      this.licenses = new ArrayList<License>();
    }
    this.licenses.add(licensesItem);
    return this;
  }

  /**
   * Get licenses
   * @return licenses
   **/
  @JsonProperty("licenses")
  @ApiModelProperty(value = "")
  public List<License> getLicenses() {
    return licenses;
  }

  public void setLicenses(List<License> licenses) {
    this.licenses = licenses;
  }

  public Image author(Author author) {
    this.author = author;
    return this;
  }

  /**
   * The image author.
   * @return author
   **/
  @JsonProperty("author")
  @ApiModelProperty(value = "The image author.")
  public Author getAuthor() {
    return author;
  }

  public void setAuthor(Author author) {
    this.author = author;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Image image = (Image) o;
    return Objects.equals(this.url, image.url) &&
        Objects.equals(this.licenses, image.licenses) &&
        Objects.equals(this.author, image.author);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, licenses, author);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Image {\n");
    
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    licenses: ").append(toIndentedString(licenses)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

