/*
 * Knowledge Graph Web Service
 * The Knowledge Graph Web Service lets you find entities and categories in the knowledge graph. This service is particularly suited to be run as a second step after the NLU Service has been used for linking ambiguous names in natural-language texts to entities. With this service, you can now explore these entities further.
 *
 * OpenAPI spec version: v2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.mpg.mpi_inf.ambiversenlu.kg.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Label
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2019-10-24T12:54:00.720Z[GMT]")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Label   {
  @JsonProperty("language")
  private String language = null;

  @JsonProperty("value")
  private String value = null;

  public Label language(String language) {
    this.language = language;
    return this;
  }

  /**
   * The language code of the label
   * @return language
   **/
  @JsonProperty("language")
  @Schema(example = "en", description = "The language code of the label")
  @JsonInclude(JsonInclude.Include.NON_EMPTY)
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public Label value(String value) {
    this.value = value;
    return this;
  }

  /**
   * The text of the label in a specific languag
   * @return value
   **/
  @JsonProperty("value")
  @Schema(description = "The text of the label in a specific languag")
  @JsonInclude(JsonInclude.Include.NON_EMPTY)
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Label label = (Label) o;
    return Objects.equals(this.language, label.language) &&
            Objects.equals(this.value, label.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(language, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Label {\n");

    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
