/*
 * VW Cloud Service
 * This is Cloud service for VW project.
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * Contact: devs@ambiverse.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.mpg.mpi_inf.ambiversenlu.kg.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotNull;
import java.util.Objects;

/**
 * MessageResponse
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2017-09-13T14:44:50.475Z")
public class MessageResponse {
  @JsonProperty("code")
  private Integer code = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("message")
  private String message = null;

  public MessageResponse(Integer code, String message) {
    this.code = code;
    this.message = message;
  }

  public MessageResponse(Integer code, String type, String message) {
    this.code = code;
    this.type = type;
    this.message = message;
  }

  public MessageResponse code(Integer code) {
    this.code = code;
    return this;
  }

  /**
   * The response code.
   * @return code
   **/
  @JsonProperty("code")
  @ApiModelProperty(example = "200", value = "The response code.")
  public Integer getCode() {
    return code;
  }

  public void setCode(Integer code) {
    this.code = code;
  }

  public MessageResponse type(String type) {
    this.type = type;
    return this;
  }

  /**
   * The type of the message
   * @return type
   **/
  @JsonProperty("type")
  @ApiModelProperty(example = "error", value = "The type of the message")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public MessageResponse message(String message) {
    this.message = message;
    return this;
  }

  /**
   * Description of the error.
   * @return message
   **/
  @JsonProperty("message")
  @ApiModelProperty(example = "There was an error. Please contact support.", required = true, value = "Description of the error.")
  @NotNull
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageResponse messageResponse = (MessageResponse) o;
    return Objects.equals(this.code, messageResponse.code) &&
        Objects.equals(this.type, messageResponse.type) &&
        Objects.equals(this.message, messageResponse.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, type, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageResponse {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

