/*
 * Knowledge Graph Web Service
 * The Knowledge Graph Web Service lets you find entities and categories in the knowledge graph. This service is particularly suited to be run as a second step after the NLU Service has been used for linking ambiguous names in natural-language texts to entities. With this service, you can now explore these entities further.
 *
 * OpenAPI spec version: v2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.mpg.mpi_inf.ambiversenlu.kg.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Meta
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2019-10-24T12:54:00.720Z[GMT]")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Meta   {
  @JsonProperty("collectionSize")
  private Integer collectionSize = null;

  @JsonProperty("creationDate")
  private Date creationDate = null;

  @JsonProperty("dumpVersion")
  private String dumpVersion = null;

  @JsonProperty("languages")
  private List<String> languages = null;

  public Meta collectionSize(Integer collectionSize) {
    this.collectionSize = collectionSize;
    return this;
  }

  /**
   * Number of elements in the knowledge graph. Elements are either entities or categories, depending on which resource the call was invoked on.
   * @return collectionSize
   **/
  @JsonProperty("collectionSize")
  @Schema(example = "560789", description = "Number of elements in the knowledge graph. Elements are either entities or categories, depending on which resource the call was invoked on.")
  public Integer getCollectionSize() {
    return collectionSize;
  }

  public void setCollectionSize(Integer collectionSize) {
    this.collectionSize = collectionSize;
  }

  public Meta creationDate(Date creationDate) {
    this.creationDate = creationDate;
    return this;
  }

  /**
   * Creation date of the knowledge graph.
   * @return creationDate
   **/
  @JsonProperty("creationDate")
  @Schema(description = "Creation date of the knowledge graph.")
  public Date getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(Date creationDate) {
    this.creationDate = creationDate;
  }

  public Meta dumpVersion(String dumpVersion) {
    this.dumpVersion = dumpVersion;
    return this;
  }

  /**
   * Version of the dump database that was used to create the knowledge graph.
   * @return dumpVersion
   **/
  @JsonProperty("dumpVersion")
  @Schema(example = "20160701", description = "Version of the dump database that was used to create the knowledge graph.")
  public String getDumpVersion() {
    return dumpVersion;
  }

  public void setDumpVersion(String dumpVersion) {
    this.dumpVersion = dumpVersion;
  }

  public Meta languages(List<String> languages) {
    this.languages = languages;
    return this;
  }

  public Meta addLanguagesItem(String languagesItem) {
    if (this.languages == null) {
      this.languages = new ArrayList<String>();
    }
    this.languages.add(languagesItem);
    return this;
  }

  /**
   * Currently supported languages.
   * @return languages
   **/
  @JsonProperty("languages")
  @Schema(description = "Currently supported languages.")
  public List<String> getLanguages() {
    return languages;
  }

  public void setLanguages(List<String> languages) {
    this.languages = languages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Meta meta = (Meta) o;
    return Objects.equals(this.collectionSize, meta.collectionSize) &&
            Objects.equals(this.creationDate, meta.creationDate) &&
            Objects.equals(this.dumpVersion, meta.dumpVersion) &&
            Objects.equals(this.languages, meta.languages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(collectionSize, creationDate, dumpVersion, languages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Meta {\n");

    sb.append("    collectionSize: ").append(toIndentedString(collectionSize)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    dumpVersion: ").append(toIndentedString(dumpVersion)).append("\n");
    sb.append("    languages: ").append(toIndentedString(languages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
